### PR TITLE
Pubsub/Monitor support

### PR DESCRIPTION
**Pull request by wilgaboury**

### CODE REVIEW

**Comment by wilgaboury** [comment]
Don't merge this PR just yet, I realized that monitors cannot be turned back into a connection, so it's drop function is actually causing an async infinite loop.

I don' think there's a good reason to support Monitor in that case because once turned into one the connection cannot be returned to the pool.

**Comment by genusistimelord** [comment]
yeah that is why I said Monitor will need to be treated as if the connection never really existed to the pool. So a Get_monitor where it gets a connection without creating anything for the pool probably would be better.

**Comment by wilgaboury** [comment]
I added a factory function to the pool so that users can access the underlying client without having to go through the pool, which should cover that use case.

**Comment by genusistimelord** [comment]
So was that able to fix the monitor issue?

**Comment by wilgaboury** [comment]
Yup should be okay to merge as long as you think the changes look good.

**Review by genusistimelord — APPROVED** [review]
everything looks good. Thank you!

**Pull request merged**
